### Get Access Token
POST http://localhost:3000/api/token
Content-Type: application/json

{
    "username": "nneko@branche.online",
    "password": "abc",
    "provider": "native"
}

### Get Access Token error handling

GET http://localhost:3000/api/token

### Get Signin view

GET http://localhost:3000/signin

### Send signin request
POST http://localhost:3000/signin
Content-Type: application/x-www-form-urlencoded

{
    "username": "nneko@branche.online",
    "password": "abc",
    "provider": "native"
}
